import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = { title: "RetainIQ",
  description: "Generated by create next app", icons: {
    icon: "https://framerusercontent.com/images/E4ASOtv32Ln0x5c9sOJ8aUHtQYg.png"} }

let initialValue = localStorage.getItem("mode")

if(initialValue === 'dark'){ const stylesheet = document.styleSheets[1],
  boxParaRule = Array.from(stylesheet.cssRules).find( (r) => (r as CSSStyleRule).selectorText ===
  "html") as CSSStyleRule; boxParaRule.style.setProperty("--mode", 'dark')
}
// else if () return initialValue == "true"; } let darkMode = getInitialState();
// document.getElementById("darkmode").checked = darkMode;

// if(darkMode){ toggleDarkMode() }

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode }>) { return (
    <html lang="en">
      <body>{children}</body>
    </html> ) }