import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = { title: "RetainIQ",
  description: "Generated by create next app", icons: {
    icon: "https://framerusercontent.com/images/E4ASOtv32Ln0x5c9sOJ8aUHtQYg.png"} }

export default function RootLayout({ children,
}: Readonly<{
  children: React.ReactNode;
}>) { return (
    <html lang="en">
      <body>{children}</body>
    </html> ) }